import { expect, test } from '@playwright/test'
import { FALLBACK_ROUTE } from '../../src/features/demo/constants'

test('abre el cockpit y permite iniciar la demostración', async ({ page, context }) => {
  let osrmCalls = 0
  await context.grantPermissions(['geolocation'], { origin: 'http://127.0.0.1:8000' })
  await context.setGeolocation({ longitude: -5.453, latitude: 36.1408 })
  await page.route('https://router.project-osrm.org/**', (route) => { osrmCalls += 1; return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ code: 'Ok', routes: [{ geometry: { coordinates: FALLBACK_ROUTE }, legs: [{ steps: [{ distance: 100, name: 'Avenida de España', maneuver: { type: 'depart', modifier: 'straight', location: FALLBACK_ROUTE[0] } }, { distance: 8_000, name: 'A-7', maneuver: { type: 'turn', modifier: 'right', location: FALLBACK_ROUTE[1] }, intersections: [{ lanes: [{ indications: ['straight'], valid: false }, { indications: ['right'], valid: true }] }] }] }] }] }) }) })
  await page.route('https://api.open-meteo.com/**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ current: { temperature_2m: 21, weather_code: 1, is_day: 1 } }) }))
  await page.route('**/osm-overpass', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ elements: [{ id: 91, type: 'node', lat: 36.1745, lon: -5.3525, tags: { amenity: 'restaurant', name: 'Venta del Camino', cuisine: 'regional', opening_hours: 'Mo-Su 12:00-23:00' } }] }) }))
  await page.route('**/geocode?**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ display_name: 'Calle Marqués de Larios, Centro Histórico, Málaga, Andalucía, España', lat: '36.7196694', lon: '-4.4215972' }]) }))
  await page.route('**/reverse-geocode?**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ display_name: 'La Línea de la Concepción, Cádiz, España', address: { city: 'La Línea de la Concepción' } }) }))
  await page.route('**/live-aircraft?**', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ updatedAt: new Date().toISOString(), aircraft: [{ id: 'abc123', callsign: 'IBE3172', coordinate: [-5.5, 36.3], altitudeM: 9200, speedKph: 710, bearingDeg: 74 }] }) }))
  const browserErrors: string[] = []
  const mapWarnings: string[] = []
  page.on('pageerror', (error) => browserErrors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') browserErrors.push(message.text())
    if (message.type() === 'warning' && /hillshade|terrain|could not be loaded|elevation maxzoom/i.test(message.text())) {
      mapWarnings.push(message.text())
    }
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /Mi Dacia/i })).toBeVisible()
  await page.getByRole('button', { name: 'Paisaje 3D', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Volver al coche' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Volver al coche' }).click()
  await expect(page.getByRole('button', { name: 'Paisaje 3D' })).toHaveAttribute('aria-pressed', 'false')
  await page.getByRole('button', { name: 'Vista global', exact: true }).click()
  await expect(page.getByLabel('Datos de la vista global')).toContainText('1 aviones reales')
  await page.getByRole('button', { name: 'Volver a navegación', exact: true }).click()
  await expect(page.getByText('La Línea de la Concepción', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Comer', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Comer en ruta' })).toBeVisible()
  await expect(page.getByText('Venta del Camino')).toBeVisible()
  await expect(page.getByRole('article').getByText(/de la ruta/)).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar', exact: true }).last().click()
  await page.getByRole('button', { name: 'Abrir menú' }).click()
  await expect(page.getByRole('heading', { name: 'Averías' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Viaje y mapa' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Pantalla y sistema' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Emergencia.*SOS/i })).toBeAttached()
  await page.getByRole('button', { name: /Ver averías/i }).click()
  await expect(page.getByRole('dialog', { name: 'Ver averías' })).toBeVisible()
  await page.getByRole('button', { name: 'Cerrar' }).click()
  await page.getByRole('button', { name: /La Línea.*San Roque/i }).click()
  await expect(page.getByRole('dialog', { name: 'Elegir recorrido' })).toBeVisible()
  await page.getByRole('button', { name: /Usar mi ubicación actual/i }).click()
  await page.getByRole('combobox', { name: 'Destino', exact: true }).fill('Calle Larios Málaga')
  await page.getByRole('button', { name: /Calle Marqués de Larios.*Centro Histórico/i }).click()
  await page.getByRole('button', { name: 'Usar esta ruta' }).click()
  await expect(page.getByText('Ubicación actual → Calle Marqués de Larios', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Avenida de España').first()).toBeVisible()
  await expect(page.getByLabel('Carriles recomendados')).toBeVisible()
  const demo = page.getByRole('button', { name: 'Probar demo' })
  await expect(demo).toBeVisible()
  const vehicleMarker = page.locator('.cockpit-vehicle-pin')
  await expect(vehicleMarker).toBeVisible()
  await expect(vehicleMarker).not.toHaveClass(/is-close/)
  await demo.click()
  await expect(page.getByText(/Ubicación actual|Calle Marqués de Larios|DEMO/i).first()).toBeVisible()
  await expect(page.getByRole('figure').first()).not.toHaveAttribute('aria-label', 'Velocidad: 0 km/h', { timeout: 5_000 })
  await expect(vehicleMarker).toHaveClass(/is-close/)
  await page.getByRole('button', { name: 'Pausar demo' }).click()
  await page.getByRole('tab', { name: 'Viaje' }).dispatchEvent('click')
  await expect(page.getByRole('heading', { name: 'Viaje actual' })).toBeVisible()
  await expect(page.getByText('km/h máxima')).toBeVisible()
  await expect(page.getByText('marcha estimada')).toBeVisible()
  await page.getByRole('tab', { name: 'Motor' }).dispatchEvent('click')
  await expect(page.getByRole('heading', { name: 'Motor' })).toBeVisible()
  await expect(page.getByText('carga motor')).toBeVisible()
  await page.getByRole('button', { name: /Conectar OBD/i }).dispatchEvent('click')
  await expect(page.getByText(/Web Bluetooth no está disponible|Bluetooth adapter not available/i)).toBeVisible()
  await page.getByRole('tab', { name: 'Viaje' }).dispatchEvent('click')
  await page.getByRole('button', { name: 'Reiniciar', exact: true }).dispatchEvent('click')
  await expect(page.getByRole('figure').first()).toHaveAttribute('aria-label', 'Velocidad: 0 km/h')
  await page.getByRole('button', { name: 'REAL GPS', exact: true }).click()
  await expect(page.getByText(/GPS REAL · ±/i)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Pausar GPS' })).toBeVisible()
  await expect.poll(() => osrmCalls, { timeout: 8_000 }).toBeGreaterThan(2)
  await page.getByRole('tab', { name: 'Motor' }).dispatchEvent('click')
  await expect(page.getByText('GPS real · motor sin OBD')).toBeVisible()
  await expect(page.getByText('–').first()).toBeVisible()
  await page.getByRole('button', { name: 'DEMO', exact: true }).click()
  await expect(page.getByText('DEMO LISTO')).toBeVisible()
  expect(browserErrors).toEqual([])
  expect(mapWarnings).toEqual([])
})
